nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["http://localhost:4200"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    allow_credentials: true
    max_age: 3600
  paths:
    "^/": null
